config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'pages/home'
   get 'crédits', to: 'pages#credits', as: :credits

    get 'about', to: 'pages#about', as: :about
    get 'test', to: 'pages#test', as: :test
    get '/search', to: 'movies#index', as: :search


  devise_for :users
  root to: 'pages#home'
  resources :movies



  resources :users


  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord

 include PgSearch
  pg_search_scope :search,
    against: [ :name, :director, :category ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  CATEGORIES = %w(Comédie Aventure Animation Drame Science-fiction Comédie-musicale)

  AGES = %w(4 5 6 7 8 9 10 11 12 13 14 15)
   mount_uploader :picture, PhotoUploader
  mount_uploader :poster, PhotoUploader
   is_impressionable counter_cache: true
   paginates_per 24

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index , unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :home, unless: :skip_pundit?


  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :current_password, :remember_me])
  end

  def default_url_options
  { host: ENV['HOST'] || 'localhost:3000' }
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :authenticate_user!, only: [:create]
  before_action :set_movie, only: [ :show, :edit, :update, :destroy]
  before_action :set_params, only: [:index]
  impressionist actions: [:show]



  def index



    #if params[:query].present?
      #sql_query = "name ILIKE :query OR director ILIKE :query"
      #@movies = Movie.where(sql_query, query:"%#{params[:query]}%").order('greatest(created_at, updated_at) desc')
    #elsif params[:age_search].present?
      #@movies = Movie.where("age <= ? ", params[:search]).order('age desc')
    #elsif params[:find].present?
      #sql_query = "category ILIKE :find"
      #@movies = Movie.where(sql_query, find:"%#{params[:find]}%").order('greatest(created_at, updated_at) desc')
    #else
      #@movies = Movie.order('greatest(created_at, updated_at) desc')
    #end

     if params[:query].present?
    @movies = Movie.search(params[:query])
    elsif params[:age_search].present?
      @movies = Movie.where("age <= ? ", params[:age_search]).order('age desc')
    elsif
    params[:find].present?
    sql_query = "category ILIKE :find"
     @movies = Movie.where(sql_query, find:"%#{params[:find]}%").order('greatest(created_at, updated_at) desc')

    else
     @movies = Movie.all
   end
    @movies_total_number = @movies.length

    @movies = @movies.page params[:page]

  end



  def show
    skip_authorization
    @movie = Movie.find(params[:id])
    impressionist(@movie)
    @same_director = Movie.where("director ILIKE ?", "%#{@movie.director}%").where.not("name ILIKE ?","%#{@movie.name}%").order('greatest(created_at, updated_at) desc')
  end

  def new
    @movie = Movie.new
    authorize @movie

  end


  def edit
    authorize @movie
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save
    redirect_to movie_path(@movie)
    authorize @movie

  end

  def update
    if @movie.update(movie_params)
    redirect_to movie_path(@movie)
    else
    render :edit
    end
    authorize @movie

  end

  def destroy
    @movie.destroy
    redirect_to movies_path
    authorize @movie

  end

  def upvote
  session[:voting_id] ||= create_unique_voting_id
  voter = VotingSession.find_or_create_by_unique_voting_id(session[:voting_id])
  voter.likes @movie

  respond_to do |format|
    format.html { redirect_back(fallback_location: root_path) }
    format.js
    end
  end
  #redirect_to movie_path(@movie)


  def downvote
  session[:voting_id] ||= create_unique_voting_id
  voter = VotingSession.find_or_create_by_unique_voting_id(session[:voting_id])
  voter.unlikes @movie
  respond_to do |format|
    format.html { redirect_back(fallback_location: root_path)}
    format.js
    end
  #redirect_to movie_path(@movie)
end

def add
  number = @movie.age
  number.downto(0) { |i| print i, " " }
  end



  private

  def movie_params
    params.require(:movie).permit(:name, :pitch, :director, :year, :created_at, :updated_at, :length, :language, :picture, :poster, :category, :age, :trailer, :scrap_number, :original_title)
  end

  def set_params
    @params = params
  end

  def set_movie
    @movie = Movie.find(params[:id])

  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about, :credits]

  def home
    @fresh_movies = Movie.order(age: :desc).limit(9)
    @random_movies = Movie.all.sample(12)

  end

  def contact
  end

  def about

  end

  def credits

  end

  def test
  end




  def non_footer_action
  do_stuff
  @skip_footer = true
end



end

app/controllers/search_controller.rb
class SearchController < ApplicationController
before_action :force_json, only: :search
skip_after_action :verify_authorized

  def index
  end

  def search
    if params[:query].present?
    @movies = Movie.search(params[:query])
    else
     @movies = Movie.all
   end
  end
  private

  def force_json
    request.format = :json
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController



before_action :set_user, only: [ :edit, :update, :destroy]

  def index


  end


  def edit
  end

  def update
    redirect_to user_path
  end

  def new
  end



  private

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

def full_age(age)
  ages = age.downto(4) { |i| print i, " " }
  puts ages
end

end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
    # avec une image dans vos assets ou une url absolue
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-138592319-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-138592319-1');
</script>


    <title><%= content_for?(:title) ? yield(:title) : "Super 8" %></title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag asset_path('roll.png'), :rel => 'icon', :type =>  'image/png' %>


    <title><%= meta_title %></title>

    <meta name="google-site-verification" content="9dEh7JRM430PX-7BBJpRSzrS8WaJeIZTTMdXVFAK3WY" />
    <meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">




    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="turbolinks-visit-control" content="reload">


  <!-- Google font -->
   <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Raleway:300,400,600,700" rel="stylesheet">
   <!-- Font awesome -->

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">



    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>

  <div id="preloader">

  <div id="status">

  </div>

</div>

<% if content_for? :nav %>
      <%= content_for :nav %>
    <% elsif content_for? :register %>
      <%= content_for :register%>
    <% else %>
      <%= render '/shared/navbar' %>
    <% end %>


<%= render 'shared/flashes' %>


    <%= yield %>
    <% unless action_name == "search" %>
 <%= render 'shared/footer' %>
 <% end %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application' %>

  <%= yield(:after_js) %>

  </body>
</html>

app/views/movies/_form.html.erb
<div class="background-new-notice ">
  <div class="bg-gradient-new-notice">
    <div class="form-group margin-top">
      <div class="container-lg margin-top">
        <div class="row">
          <div class="col-sm-6 col-sm-offset-3">
            <div class="background-white-new-notice">
      <br/>

      <%= simple_form_for @movie do |f| %>
      <%= f.input :scrap_number, label: "scrap number" %>
      <%= f.input :name, label: "Titre du film"%>
      <%= f.input :age, collection: Movie::AGES, label: "Tranche d'âge", prompt: "Choissisez un âge" %>
      <%= f.input :category, label: "Catégorie", prompt: "Choissisez une catégorie" %>
      <%= f.input :director, label: "Metteur en scène"%>
      <%= f.input :year, as: :date, start_year: Date.today.year - 100,
                              end_year: Date.today.year,
                              order: [:year], :include_blank => '(All)', label: "Année de sortie"  %>
      <%= f.input :original_title, label: "Quel est le titre original du film" %>
      <%= f.input :language, label: "Dans quelle langue a été tournée le film"%>
      <%= f.input :length, label: "Quelle est la durée du film?" %>
      <%= f.input :pitch, as: :text, label: "Quel est le synopsis?" %>
     <%= f.input :picture, label: "Voulez-vous ajouter une photo?" %>
      <%= f.input :picture_cache, as: :hidden %>
      <%= f.input :poster, label: "voulez-vous ajouter une affiche?" %>
      <%= f.input :poster_cache, as: :hidden %>
      <%= f.input :trailer, label: "trailer" %>

      <%= f.button :submit, class: "btn btn-success" %>
      <% if @movie.errors.any? %>
          <div class="errors-container">
            <ul>
              <% @movie.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
    <% end %>


            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/edit.html.erb
<% content_for :register, render('shared/navbar_register') %>
<%= render "form" %>

app/views/movies/index.html.erb
<body style="background-color: white">
<% content_for :nav, render('shared/navbar_index') %>




<div class= "container thousand-one margin-sixty">
  <!-- form to add specific filters and refresh this page -->

<p class="text-justify" id="explain"><strong>Vous</strong> pouvez <strong>chercher</strong> des <strong>films</strong><br>par <span>titre</span>, par <span>réalisateur.rice</span>, </br> par <span>catégorie</span> ou par <span>âge </span> de <strong>l'enfant</strong>.</p><br/>

<div class="search-tag">

      <%= react_component("Search") %>


       <!--<div class=" form-group">
          <%= form_tag movies_path, method: :get do %>
          <%= label_tag :query, "Chercher par titre ou par réalisateur:" %>
           <div class="form-inline search">
              <%= text_field_tag :query,
              params[:query],
              class: "form-control"
              %>
              <%= submit_tag "Go!", class: 'button btn' %>

          <%end %>
          </div>
      </div>

    </div> -->


  <!-- form to add specific filters and refresh this page -->

  <!-- <div class="col-md-4">
       <div class="form-group raleway">
          <%= form_tag movies_path, method: :get do %>
          <%= label_tag :find, "Trier par catégories:"%>
          <div class="form-inline search">
          <%= select_tag :find, options_for_select(Movie::CATEGORIES), include_blank: true, class:"form-control" %>
            <%= submit_tag "Go!", class: 'button btn' %>
          </div>

       <% end %>

      </div>
    </div> -->



  <%= form_tag movies_path, method: :get do %>
          <!--<%= label_tag :find, "Trier par categories:"%> -->
          <div class="form-group">
              <%= select_tag :find, options_for_select(Movie::CATEGORIES), :prompt => "Categorie",class:"form-control", :onchange=>'this.form.submit();' %>

          </div>

      <% end %>


          <%= form_tag movies_path, method: :get do %>
          <!--<%= label_tag :age_search, "Trier par âges:"%> -->
          <div class="form-group">
              <%= select_tag :age_search, options_for_select(Movie::AGES), :prompt => "Age",class:"form-control", :onchange=>'this.form.submit();' %>

          </div>

      <% end %>

<%= link_to "Tous les films", movies_path, class:"btn btn-green reset" %>


</div>





</div>

  <!-- form to add specific filters and refresh this page -->


    <p style= "color:white">&#x25BD; </p>

</div>



<!--<div id="results">
<% if params[:query].present? %>
<p class="text-center margin-top-fifty"> <strong>Les films correspondants à votre recherche "<%= params[:query]%>"</strong> </p>

  <% if @movies_total_number == 0 %>
  <p class= "text-center">Oups, nous n'avons pas cette référence dans la base &#x1F64A </p>
  <p class= "text-center">Pour nous envoyer vos suggestions <%= link_to "c'est ici", about_path%>.</p>
  <%end%>
  <%if @movies_total_number > 0 %>
  <p class="text-center"> <%= @movies_total_number%></p>
  <%end%>
  <% end %>

<% if params[:search].present? %>
<p class="text-center margin-top-fifty"> Les films pour les enfants de <span><%= params[:search]%> ans </span> et moins </p>

<% end %>

</div> -->


<br/>
<div class="container padding-bottom">
  <% if params[:query].present? %>
    <% if @movies_total_number > 0 %>
        <p class= "text-center result">Nombre de résultats correspondant à votre recherche: <span><%= @movies.count %></span> </p>
    <% end %>
  <% end %>

  <% if params[:age_search].present? %>
    <% if @movies_total_number > 0 %>
        <p class= "text-center result"> <strong><%= @movies.count %> </strong> films pour les enfants de <span> <%= params[:age_search] %> </span> ans (et moins) </p>
    <% end %>
  <% end %>

  <% if params[:find].present? %>
    <% if @movies_total_number > 0 %>
        <p class= "text-center result"> <strong><%= @movies.count %> </strong> films de la catégorie <span> <%= params[:find] %> </span> </p>
    <% end %>
  <% end %>

  <div class="row">
    <% @movies.each do |movie| %>
    <div class="col-xs-12 col-sm-4">

      <!-- insert <div class="card"> -->



          <div class="card-body">
             <div class="title-card text-center"><p style= "color: #43465b; font-weight: bold; font-family: Raleway; font-size: 18px;"> <%=movie.category%></p>
            </div>
             <div class="card-picture"  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(
              <%= cloudinary_url movie.picture, height: 300, :crop => :scale, :alt=>"Image du film #{movie.name}" %>

             );">

                  <p><%=movie.name %></p>


                  <a href="<%= movie_url(movie) %>" >
                    <div class="card-hover">
                  <h4 >Un film de <%=movie.director%></h4>
                  </div>
                  </a>
              </div>
              <div class="card-likes">
              <ul class="list-inline">
                <ul class="list-inline">
                  <li><i class="fa fa-heart red"></i> À partir de <%= movie.age %> ans</li>
                  <li><i class="fa fa-eye greeny"></i> <%=movie.impressionist_count%>
                  </li>

                </ul>
              </ul>

            </div>

          </div>


    </div>
    <% end %>

    <% if @movies_total_number == 0 %>
      <p class= "text-center">Aucun résultat pour <strong>"<%= params[:query] %>"</strong></p>
      <p class= "text-center"> Envoyez nous vos <%= link_to "suggestions", about_path%>, nous les examinerons avec plaisir!</p>
    <%end%>






  </div>

  <div class="container text-center margin-top">
  <%= paginate @movies, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm pagination-centered"%>
   </div>

</div>

</body>

app/views/movies/new.html.erb
<%= render 'form', movie: @movie %>

app/views/pages/about.html.erb
<body style= "background-color: white">
    <% content_for :nav, render('shared/navbar_about') %>
    <% content_for(:title) do %> À propos
<% end %>
<div class="container presentation">

<div class="row">

<div class="col-xs-12 col-sm-3 " id="photo-presentation">
 <%= image_tag "me.JPG", height: 400,  :alt => "Laure années 80 île de Ré"%>
</div>

<div class="col-xs-12 col-sm-6 col-sm-offset-1">
<p class="text-justify">J'ai grandis dans les années 80 et le cinéma a beaucoup compté dans la construction de mon imaginaire.<br/><br/>Super 8 est un carnet de transmission cinématographique à mes enfants. </br> </br> La sélection est absoluement subjective et beaucoup d'oeuvres ne sont pas spécifiquement destinées à un jeune public. </br><br/>
<p class="margin-twenty"><b>Pour me contacter</b>: contact[at]super-8.io</p>
<p class="credits-link"><b>Les crédits</b>: <%= link_to "c'est par ici", credits_path %></p>

</div>
</div>

</div>


</body>

app/views/pages/test.html.erb
<div class="container" style="margin-top: 50px">
  <p>Hello</p>
<%= javascript_pack_tag "hello_react" %>
<%= react_component("Search") %>

</div>

app/views/search/index.html.erb
 <h1><%= params[:query] %> (<%= @movies.count %> results)</h1>

  <div>
    <% @movies.each do |movie| %>
      <a href="<%= movie_path(movie) %>">

          <p><%= movie.name %></p>
          <p><%= movie.director %></p>



      </a>
    <% end %>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon black-nav navbar-fixed-top ">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.svg", height: 20 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">





    <%= link_to "Voir tous les film", movies_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "À propos", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Acceuil", pages_home_path, class: "navbar-wagon-item navbar-wagon-link" %>



      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
         <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Trouver un film", movies_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to "À propos", about_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        </ul>
    </div>
  </div>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Voir tous films", movies_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Home", root_path, class: "navbar-wagon-brand"%></li>


      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_about.html.erb
<div class="navbar-wagon black-nav navbar-fixed-top ">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.svg", height: 20 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <%= link_to "Trouver un film", movies_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Crédits", credits_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% if current_user && current_user.admin? %>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
                 <%= t(".sign_out", default: "Logout") %> </li>
              <% end %>
        <% else %>
        <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></i></li>
        <% end %>



      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
         <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Trouver un film", movies_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to "À propos", about_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <% if current_user && current_user.admin? %>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
                 <%= t(".sign_out", default: "Logout") %> </li>
              <% end %>
        <% else %>
        <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></i></li>
        <% end %>
        </ul>
    </div>
  </div>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Les films", movies_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
         <% if current_user && current_user.admin? %>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
                 <%= t(".sign_out", default: "Logout") %> </li>
              <% end %>
        <% else %>
        <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></i></li>
        <% end %>
        <li><%= link_to "Home", root_path, class: "navbar-wagon-brand"%></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_home.html.erb
<div class="navbar-wagon transparent-nav navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "film-roll-true-red.svg", height: 50%>

  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "Voir tous les films", movies_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "À propos", about_path, class: "navbar-wagon-item navbar-wagon-link" %>



      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
         <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Voir tous les films", movies_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to "À propos", about_path, class: "navbar-wagon-item navbar-wagon-link" %></li>

        </ul>
    </div>
  </div>
</div>

  <!-- Dropdown list appearing on mobile only -->
<div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li> <%= link_to "Voir tous les films", movies_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "À propos", about_path, class: "navbar-wagon-item navbar-wagon-link" %></li>

      </ul>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_index.html.erb
<div class="navbar-wagon transparent-nav navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "film-roll-true-red.svg", height: 50%>

  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <%= link_to "À propos", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Acceuil", pages_home_path, class: "navbar-wagon-item navbar-wagon-link" %>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
         <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "À propos", about_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to "Acceuil", pages_home_path, class: "navbar-wagon-item navbar-wagon-link" %></li>

        </ul>
    </div>
  </div>
</div>

  <!-- Dropdown list appearing on mobile only -->
<div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "À propos", about_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Acceuil", pages_home_path, class: "navbar-wagon-item navbar-wagon-link" %></li>

      </ul>
      </ul>
    </div>
  </div>
</div>